In [4]:
import numpy as np

In [65]:
import pandas as pd

In [67]:
#리스트를 `x`를 numpy 배열로 `array1`에 저장합니다.
# 리스트 선언
x = [1, 2, 3, 4, 5, 6]

# numpy 배열로 변환
array1 = np.array(x)

# 결과 출력
array1

array([1, 2, 3, 4, 5, 6])

In [69]:
# 모든 원소가 0인 3×3의 배열을 `array2`에 저장합니다.
array2 = np.zeros((3, 3))
array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# 모든 원소가 1인 2×5의 배열을 `array3`에 저장합니다.
array3 = np.ones((2, 5))
array3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
# 0 이상 1 미만의 랜덤 값을 갖는 5×3의 배열을`array4`에 저장합니다.
array4 = np.random.random((5, 3))
array4

array([[0.39954138, 0.24666089, 0.45226855],
       [0.09501563, 0.54411735, 0.20415738],
       [0.92499018, 0.04982187, 0.87642293],
       [0.09982438, 0.77511921, 0.47983081],
       [0.2432929 , 0.02406387, 0.42364641]])

In [75]:
# 0부터 9까지의 값을 원소로 하는 1×10 배열을`array5`에 저장합니다.

array5 = np.arange(0, 10, 1)  
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# `array1`의 첫 번째 column 벡터와 두 번째 column 벡터를 더한 결과를 `array2`에 저장해봅시다.
array1 = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]]) 

array2 = array1[:, 0] + array1[:, 1]

array2

array([ 3,  9, 15])

In [79]:
# `array1`의 첫 번째 row 벡터와 두 번째 row 벡터를 뺀 결과를 `array3`에 저장해봅시다.

array3 = array1[0, :] - array1[1, :]
array3

array([-3, -3, -3])

In [81]:
# `array2`과 `array3`을 곱한 결과를 `array4`에 저장해봅시다.

array4 = array2 * array3 
array4

array([ -9, -27, -45])

In [83]:
# `array5`는 `array2`, `array3`, `array4` 값을 column으로 이어 붙인 배열입니다.

array5 = array5 = np.column_stack((array2, array3, array4))
array5

array([[  3,  -3,  -9],
       [  9,  -3, -27],
       [ 15,  -3, -45]])

In [85]:
# `array1`을 `array5`로 나눈 결과를 `array6`에 저장해봅시다.
array6 = array1/array5
array6

array([[ 0.33333333, -0.66666667, -0.33333333],
       [ 0.44444444, -1.66666667, -0.22222222],
       [ 0.46666667, -2.66666667, -0.2       ]])

In [91]:
# 1차원 데이터를 선언하여 ***Series*** 자료형 데이터를 생성하고, 생성한 Series의 name은 `age`로 설정하세요.
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
age_series = pd.Series(x, name='age')
age_series

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: age, dtype: int64

In [93]:
# Dictionary 데이터 `class_name`을 ***Series 형*** 데이터로 생성하여 변수 `class_series` 에 저장하세요.
class_name = {'국어' : 'Korean', '수학' : 'Math', '영어' : 'English', '물리' : 'Physics', '화학' : 'Chemistry'}
class_series = pd.Series(class_name)

class_series

국어       Korean
수학         Math
영어      English
물리      Physics
화학    Chemistry
dtype: object

In [99]:
# 2차원 리스트를 전달하여 ***DataFrame*** 자료형 데이터를 생성하고, 생성한 DataFrame 데이터를 변수 `df` 에 저장하세요.
a = [[10, 20], [30, 40], [40, 50]]
df = pd.DataFrame(a, columns=["Column1", "Column2"])

print(df)

   Column1  Column2
0       10       20
1       30       40
2       40       50


In [105]:
# 아래와 같이 DataFrame 변수인 `human`을 만들어보세요. (`pd.DataFrame()`을 활용하세요.)

age = [20, 15, 30, 25, 35]
weight = [68.5, 60.3, 53.4, 74.1, 80.7]
height = [180, 165, 155, 178, 185]
human = pd.DataFrame([age, weight, height], index=["age", "weight", "height"])

human

0      1      2      3      4
age      20.0   15.0   30.0   25.0   35.0
weight   68.5   60.3   53.4   74.1   80.7
height  180.0  165.0  155.0  178.0  185.0

In [111]:
# `loc()` ,`iloc()`을 이용해 `age`를 추출해보세요.

age_loc = human.loc["age"]
age_iloc = human.iloc[0]

age_loc
age_iloc

0    20.0
1    15.0
2    30.0
3    25.0
4    35.0
Name: age, dtype: float64

In [113]:
# `loc() `, `iloc()`을 이용해 `weight`와 `height`만 추출해보세요.

wh_loc = human.loc[["weight", "height"]]
wh_iloc = human.iloc[1:3]

wh_loc
wh_iloc

0      1      2      3      4
weight   68.5   60.3   53.4   74.1   80.7
height  180.0  165.0  155.0  178.0  185.0

In [117]:
# 새로운 데이터 `sex`를 `human`에 추가해보세요.

sex = ["Female", "Male", "Female", "Female", "Male"]
human.loc["sex"] = sex

human

0      1       2       3      4
age       20.0   15.0    30.0    25.0   35.0
weight    68.5   60.3    53.4    74.1   80.7
height   180.0  165.0   155.0   178.0  185.0
sex     Female   Male  Female  Female   Male

In [119]:
# `drop()`으로 `human`에서 `height`를 삭제해보세요.

human_updated = human.drop(["height"], axis=0)
human_updated

0     1       2       3     4
age       20.0  15.0    30.0    25.0  35.0
weight    68.5  60.3    53.4    74.1  80.7
sex     Female  Male  Female  Female  Male

In [127]:
# Pandas 연산 함수를 써서 행렬 연산을 해보세요.
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"])
df2 = pd.DataFrame([[9, 8, 7], [6, 5, 4], [3, 2, 1]], columns=["A", "B", "C"])

result_add = df1.add(df2, fill_value=0)  # 덧셈
result_sub = df1.sub(df2, fill_value=0)  # 뺄셈
result_mul = df1.mul(df2, fill_value=0)  # 곱셈
result_div = df1.div(df2, fill_value=1)  # 나눗셈

print("덧셈", result_add)
print("뺄셈", result_sub)
print("곱셈", result_mul)
print("나눗셈", result_div)

덧셈     A   B   C
0  10  10  10
1  10  10  10
2  10  10  10
뺄셈    A  B  C
0 -8 -6 -4
1 -2  0  2
2  4  6  8
곱셈     A   B   C
0   9  16  21
1  24  25  24
2  21  16   9
나눗셈           A     B         C
0  0.111111  0.25  0.428571
1  0.666667  1.00  1.500000
2  2.333333  4.00  9.000000


In [131]:
# sort_values()`를 사용해 오름차순 및 내림차순 정렬을 해보세요.

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 22, 35, 29],
    "Score": [88, 75, 95, 80, 90]
}

df = pd.DataFrame(data)
df_sorted_asc = df.sort_values(by="Age", ascending=True)
df_sorted_desc = df.sort_values(by="Age", ascending=False)

print("오름차순")
print(df_sorted_asc)

print("내림차순")
print(df_sorted_desc)

오름차순
      Name  Age  Score
2  Charlie   22     95
0    Alice   25     88
4      Eve   29     90
1      Bob   30     75
3    David   35     80
내림차순
      Name  Age  Score
3    David   35     80
1      Bob   30     75
4      Eve   29     90
0    Alice   25     88
2  Charlie   22     95


In [135]:
4. `to_csv()`, `read_csv()`를 사용해 데이터프레임을 저장하고 불러와보세요.

df.to_csv("data.csv", index=False)
df_loaded = pd.read_csv("data.csv")

SyntaxError: invalid syntax (2054071031.py, line 1)